(async()=>{
 const form=document.querySelector("#match-form"),fileInput=document.querySelector("#cv-file"),textInput=document.querySelector("#cv-text"),status=document.querySelector("#match-status"),results=document.querySelector("#match-results"),title=document.querySelector("#match-title");
 let data=[];try{data=await (await fetch("data/opportunities.json")).json()}catch{status.textContent="Could not load quests. Please try again.";return}
 const stopWords=new Set("and the for with from that this your have are you will into our their about which using while where what who how not can all any one two more".split(" "));
 const tokens=value=>[...new Set((value.toLowerCase().match(/[a-z][a-z0-9+#.-]{2,}/g)||[]).filter(x=>!stopWords.has(x)))];
 fileInput.addEventListener("change",()=>{const file=fileInput.files[0];if(!file)return;if(file.type.startsWith("text/")||/\.(txt|md)$/i.test(file.name)){const reader=new FileReader();reader.onload=()=>{textInput.value=String(reader.result);status.textContent=`Loaded ${file.name}. Ready to match.`};reader.readAsText(file)}else status.textContent=`${file.name} selected. Paste its text below for the most accurate match.`});
 form.addEventListener("submit",event=>{event.preventDefault();const profile=tokens(textInput.value);if(profile.length<2){status.textContent="Add at least two skills, subjects or experience keywords first.";return}const scored=data.map(item=>{const searchable=tokens([item.title,item.description,item.category,item.experience,item.qualifications.join(" "),item.requirements.join(" ")].join(" "));const hits=profile.filter(token=>searchable.includes(token));return {...item,score:hits.length,matched:hits}}).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title)).slice(0,8);title.textContent=scored.length?`${scored.length} QUEST MATCHES`:`NO DIRECT MATCHES YET`;status.textContent=scored.length?`Matched ${profile.length} keywords. Review the requirements before applying.`:"No direct keyword matches. Try adding tools, subjects, job titles or skills from your CV.";results.innerHTML=scored.length?scored.map(item=>`<article class="match-card"><div class="match-score">${Math.min(99,Math.round((item.score/profile.length)*100))}%<br>MATCH</div><div><h3>${esc(item.title)}</h3><p>${esc(item.organisation)} · ${esc(item.experience)} · ${item.matched.slice(0,5).map(esc).join(", ")}</p></div><a class="btn small" href="opportunity.html?id=${encodeURIComponent(item.id)}">VIEW QUEST</a></article>`).join(""):"<div class=\"empty\"><p>Try adding skills, software, subjects, certificates or job titles from your CV.</p></div>"});
 function esc(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
})();
